{{- if .Values.ui.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "noperator.name" . }}
    app.kubernetes.io/component: ui
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "noperator.resourceName" (dict "suffix" "ui" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- end }}
